server:
  port: 7777
spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      server-addr: 192.168.56.129:8848
