server:
  port: 7777
spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      server-addr: 172.20.172.244:8848
